// SPDX-License-Identifier: GPL-2.0+
/*
 * SATA OOB (COMRESET/COMWAKE) trigger command for cv84x6 DWC AHCI.
 *
 * Generates out-of-band (OOB) signalling for scope measurement:
 *   comreset - COMRESET OOB burst (PxSCTL.DET = 1 -> 0), no device needed
 *   comwake  - COMWAKE OOB burst (Partial/Slumber power-management entry)
 *
 * OOB signalling (COMRESET/COMINIT/COMWAKE) is generated by the link state
 * machine and is separate from the BIST data patterns (BISTCR.PATTERN). It is
 * a short burst followed by a long idle gap, not a continuous waveform.
 *
 * Ports 0/1 -> satac0 @0x21310000, ports 2/3 -> satac1 @0x21350000.
 */

#include <common.h>
#include <command.h>
#include <dm.h>
#include <ahci.h>
#include <asm/io.h>
#include <linux/delay.h>

#define DWC_SATA_PORTS_PER_CTRL	2

/* AHCI per-port register block: base + 0x100 + port*0x80 */
#define AHCI_PxCMD	0x18	/* Port command */
#define AHCI_PxSSTS	0x28	/* SStatus */
#define AHCI_PxSCTL	0x2c	/* SControl */

#define PORT_CMD_ICC_ACTIVE	(0x1 << 28)	/* interface -> active */
#define PORT_CMD_ICC_PARTIAL	(0x2 << 28)	/* interface -> partial */

static void *sata_oob_get_base(int port)
{
	struct udevice *dev;
	struct ahci_uc_priv *uc_priv;
	int ctrl = port / DWC_SATA_PORTS_PER_CTRL;
	int rc;

	rc = uclass_get_device(UCLASS_AHCI, ctrl, &dev);
	if (rc) {
		printf("sata_oob: AHCI controller %d not probed, run 'sata init' first (err=%d)\n",
		       ctrl, rc);
		return NULL;
	}

	uc_priv = dev_get_uclass_priv(dev);
	if (!uc_priv || !uc_priv->mmio_base) {
		printf("sata_oob: no mmio base\n");
		return NULL;
	}

	return (void *)uc_priv->mmio_base;
}

static void sata_oob_comreset(void *base, int port)
{
	int p = port % DWC_SATA_PORTS_PER_CTRL;
	void *sctl = base + 0x100 + p * 0x80 + AHCI_PxSCTL;
	u32 v = readl(sctl);

	/* DET=1 asserts phy_reset (COMRESET); >=1ms; DET=0 sends COMRESET OOB */
	v &= ~0xf;
	writel(v | 0x1, sctl);
	mdelay(1);
	writel(v, sctl);
	mdelay(10);	/* let the OOB burst complete before dumping status */
}

static void sata_oob_comwake(void *base, int port)
{
	int p = port % DWC_SATA_PORTS_PER_CTRL;
	void *cmd = base + 0x100 + p * 0x80 + AHCI_PxCMD;
	u32 v = readl(cmd);

	/*
	 * Request Partial power management: the PMREQ/PMACK handshake emits
	 * COMWAKE OOB on the wire. Note this only works with a device attached
	 * (link must be L_IDLE); with no device the request is ignored.
	 */
	v = (v & ~(0xf << 28)) | PORT_CMD_ICC_PARTIAL;
	writel(v, cmd);
	mdelay(10);
	/* back to active (also emits COMWAKE on the way out) */
	v = (v & ~(0xf << 28)) | PORT_CMD_ICC_ACTIVE;
	writel(v, cmd);
	mdelay(10);
}

static void sata_oob_dump(void *base, int port)
{
	int p = port % DWC_SATA_PORTS_PER_CTRL;
	void *cmd = base + 0x100 + p * 0x80 + AHCI_PxCMD;
	void *ssts = base + 0x100 + p * 0x80 + AHCI_PxSSTS;
	void *sctl = base + 0x100 + p * 0x80 + AHCI_PxSCTL;
	u32 c = readl(cmd), s = readl(ssts), t = readl(sctl);

	printf("--- sata_oob regs: port %d (ctrl %d) ---\n",
	       port, port / DWC_SATA_PORTS_PER_CTRL);
	printf("  P%dCMD   0x%03x = 0x%08x  [ICC=0x%x]\n",
	       p, 0x100 + p * 0x80 + AHCI_PxCMD, c, (c >> 28) & 0xf);
	printf("  P%dSSTS   0x%03x = 0x%08x  [DET=0x%x SPD=%u IPM=0x%x]\n",
	       p, 0x100 + p * 0x80 + AHCI_PxSSTS, s,
	       s & 0xf, (s >> 4) & 0xf, (s >> 8) & 0xf);
	printf("  P%dSCTL   0x%03x = 0x%08x  [DET=0x%x IPM=0x%x]\n",
	       p, 0x100 + p * 0x80 + AHCI_PxSCTL, t,
	       t & 0xf, (t >> 8) & 0xf);
}

static int do_sata_oob(struct cmd_tbl *cmdtp, int flag, int argc,
		       char *const argv[])
{
	void *base;
	int port_lo = 0, port_hi = 3, p;
	int comwake = 0;

	if (argc < 2)
		return CMD_RET_USAGE;

	if (!strcmp(argv[1], "comreset")) {
		comwake = 0;
	} else if (!strcmp(argv[1], "comwake")) {
		comwake = 1;
	} else {
		return CMD_RET_USAGE;
	}

	if (argc >= 3 && strcmp(argv[2], "all")) {
		port_lo = (int)dectoul(argv[2], NULL);
		if (port_lo < 0 || port_lo > 3) {
			printf("sata_oob: invalid port %d (0-3 or all)\n", port_lo);
			return CMD_RET_FAILURE;
		}
		port_hi = port_lo;
	}

	for (p = port_lo; p <= port_hi; p++) {
		base = sata_oob_get_base(p);
		if (!base)
			return CMD_RET_FAILURE;

		if (comwake)
			sata_oob_comwake(base, p);
		else
			sata_oob_comreset(base, p);

		sata_oob_dump(base, p);
	}

	return CMD_RET_SUCCESS;
}

U_BOOT_CMD(
	sata_oob, 3, 1, do_sata_oob,
	"SATA OOB (COMRESET/COMWAKE) trigger (DWC AHCI, 4 ports)",
	"comreset [port|all]   - send COMRESET OOB burst (no device needed)\n"
	"sata_oob comwake  [port|all]   - send COMWAKE OOB burst (needs device)\n"
	"  port 0-3 or 'all' (default all)\n"
	"Run 'sata init' first."
);
